name: Deploy to Droplets

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.DROPLET_IPS }} >> ~/.ssh/known_hosts

    - name: Deploy to droplets
      env:
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        DROPLET_IPS: ${{ secrets.DROPLET_IPS }}
      run: |
        IFS=',' read -ra ADDR <<< "$DROPLET_IPS"
        for ip in "${ADDR[@]}"; do
          echo "Deploying to $ip"
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SSH_USERNAME@$ip << 'EOF'
            cd /var/www/dimas/html/
            git pull https://oauth2:${{ secrets.GH_TOKEN }}@github.com/elmerMg0/repo.git main
            sudo systemctl restart apache2
        EOF
        done

