name: Deploy to Droplets

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy to droplet
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        DROPLET_IP: ${{ secrets.DROPLET_IPS }}
      run: |
        echo "Deploying to $DROPLET_IP"
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$DROPLET_IP <<EOF
          cd /var/www/dimas/html/
          git pull origin main
          sudo systemctl restart apache2
        EOF

